version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=
    restart: unless-stopped
