version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    ports:
      - '8998:8080'
    volumes:
      - ./appdata/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./appdata/extraConfigs:/configs
      - ./appdata/customFiles:/customFiles/
    restart: unless-stopped